### ISSUE TITLE
New widgets

### ISSUE THREAD

**Issue by mosaab1** [jmulet/moodle-tiny_widgethub#24]
In this thread, I’ll continue sharing my newly created widgets. I warmly welcome your feedback and suggestions for better coding practices, as I’m still in the process of learning your plugin. My goal is to contribute as much as possible toward building a full-featured page/block builder.
The first widget is for Font Awesome icons—it enhances the existing one by offering an improved, user-friendly copy-and-paste interface with additional styling options.

`key: icon
name: Icon
category: Media
instructions: >-
  Please visit the <a href="https://mosaab1.github.io/fontawesome/"
  target="_blank"> Font Awesome page</a> to locate and copy the icon name you
  wish to use.
template: >
  <i class="fa-solid fa-{{iconName}} fa-{{animation}} fa-{{iconSize}}x"
  style="color: {{iconColor}};"></i>
parameters:
  - name: iconName
    title: Icon name
    tip: Use the link above to find and copy the desired icon name.
    value: font-awesome
  - name: animation
    title: Animation
    value: false
    options:
      - none
      - beat
      - beat-fade
      - bounce
      - fade
      - shake
      - spin
      - spin-reverse
      - spin-pulse
  - name: iconColor
    title: Icon Color
    type: color
    value: '#000000'
  - name: iconSize
    title: Icon Size
    tip: Choose the size of the icon.
    type: numeric
    min: 1
    max: 10
    value: 2
author: Mossaab Mohamed Ali <mosab@mussaab.com>
version: 1.0.0
`
The file used in this widget can be found here: https://github.com/mosaab1/fontawesome/blob/main/index.html . Please feel free to review and include it in the plugin if it doesn't significantly impact the bundle size.
Looking ahead, I hope we can introduce an "Icon" as "Type" similar to image and color—as it would be a valuable addition for design-related use cases.

**Comment by mosaab1** [comment]
It is in the attached file , github removes template from the code when posting

`  <i class="fa-solid fa-{{iconName}} fa-{{animation}} fa-{{iconSize}}x"
  style="color: {{iconColor}};"></i>`

**Comment by jmulet** [comment]
It looks good!
Several recommendations:
1- Prepend the key with your username to avoid collisions with other widgets, so `key: mosaab1_icon`
2- `animation` is a select parameter, so the property `value` must match one of the defined in `options``
3- It is recommended to add `&nbsp;` before and after the template to make editing with tinyMCE easier.

**Comment by mosaab1** [comment]
Thanks for the recommendations! I’ve made the updates—please feel free to review.
```
key: mossaab_icon
name: Icon
category: Media
instructions: >-
  Please visit the <a href="https://mosaab1.github.io/fontawesome/"
  target="_blank"> Font Awesome page</a> to locate and copy the icon name you
  wish to use.<br> This widget supports Moodle version 4.0 and later.
template: >
  <span> &nbsp; </span> 
  <i class="fa-solid fa-{{iconName}} fa-{{animation}} fa-{{iconSize}}x"
  style="color: {{iconColor}};"></i> 
  <span> &nbsp; </span>
parameters:
  - name: iconName
    title: Icon name
    tip: Use the link above to find and copy the desired icon name.
    value: font-awesome
  - name: animation
    title: Animation
    value: none
    options:
      - none
      - beat
      - beat-fade
      - bounce
      - fade
      - shake
      - spin
      - spin-reverse
      - spin-pulse
  - name: iconColor
    title: Icon Color
    type: color
    value: '#000000'
  - name: iconSize
    title: Icon Size
    tip: Choose the size of the icon.
    type: numeric
    min: 1
    max: 10
    value: 2
author: Mossaab Mohamed Ali <mosab@mussaab.com>
version: 1.0.0
```
Also, is it okay to use my real name instead of my GitHub username?
