### ISSUE TITLE
HTML comments being wrapped in <p> tags.

### ISSUE THREAD

**Issue by BirdyOz** [jmulet/moodle-tiny_widgethub#31]
If a widgethub template includes an HTML comment, when inserted into the TinyMCE editor, this comment is sometimes (but not always) wrapped inside a `<p>` tag.   This throws out the whitespace and makes the code more difficult to read.   Additional empty `p` tags are sometimes thrown in.

YAML fille:

```yaml
key: mp-box-learning-activity
name: Learning Activity Box
category: UI
instructions: |
  Add the details of your Learning Activity
template: |
  <!-- Start of Box-Activity -->
  <div class="clearfix container-fluid"> </div>
  <div class="card mt-1 mb-1 clearfix w-100">
      <div class="card-body">
          <h4 class="card-title text-danger"><i aria-hidden="true" class="fa fa-tasks"></i> Learning Activity - {{title}}</h4>
          <p>{{description}}</p>
      </div>
  </div>
  <!-- End of Box-Activity -->
parameters:
  - name: title
    value: '[Title goes here]'
    title: Enter a title for this activity
  - name: description
    value: '[Description goes here]'
    title: Enter a brief description of the activity
    type: textarea
author: Greg Bird <greg.bird.oz@gmail.com>
version: 1.0.0
```

Resulting HTML in TinyMCE editor (NB we are also using your SourceCode Pro plugin)

```html
<p><!-- Start of Box-Activity --></p>
<div class="clearfix container-fluid"> </div>
<div class="card mt-1 mb-1 clearfix w-100">
    <div class="card-body">
        <h4 class="card-title text-danger"><i aria-hidden="true" class="fa fa-tasks"></i> Learning Activity - [Title goes here]</h4>
        <p>[Description goes here]</p>
    </div>
</div>
<!-- End of Box-Activity -->
<p> </p>
<p></p>

```

Observe that:

* The first comment is wrapped in a `<p>` tag, but not the second
* There are two additional and empty  `<p>` tags below the snippet (one contains a whitespace character, the other does not.

There is an old TinyMCE issue here, that may be related:

<ul>
	<li><strong><a href="https://github.com/tinymce/tinymce/issues/4188" target="_blank">[insertContent command auto adds p tags for comment nodes instead of keeping HTML intact · Issue #4188 · tinymce/tinymce](https://github.com/tinymce/tinymce/issues/4188)</a></strong></li>
</ul>
